name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/macandkaj/motur_rpi3bp_dev:243ab69a246a

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake - Debug
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build - Debug
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Configure CMake - Release
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build - Release
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

